version: '3.8'

services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80" # Port 80 dans le conteneur est accessible via le port 8080
    volumes:
      - ./frontend:/usr/share/nginx/html # Montre le dossier frontend
      - ./logs/nginx:/var/log/nginx      # Sauvegarde les logs Nginx
    networks:
      - hackathon_network

  backend:
    build: ./Backend
    ports:
      - "5000:5000" # Le port 5000 du conteneur est exposé sur la machine hôte
    depends_on:
      - db # Le backend attend que la base de données démarre avant de s’exécuter
    volumes:
      - ./Backend:/app # Montre le code source backend
    networks:
      - hackathon_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root # Mot de passe utilisateur root
      MYSQL_DATABASE: hackathon # Création d'une base de données par défaut
    ports:
      - "3306:3306" # Expose le port par défaut de MariaDB
    volumes:
      - db_data:/var/lib/mysql # Volume persistant pour les données
    networks:
      - hackathon_network

volumes:
  db_data: # Volume persistant pour la base de données

networks:
  hackathon_network:
    driver: bridge # Réseau Docker pour connecter les services
