services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    networks:
      - hackathon_network

  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hackathon_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deploiement
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:

