services:
  frontend:
    image: nginx:latest
    container_name: h-j-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
    networks:
      - hackathon_network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: h-j-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hackathon_network

  db:
    image: mariadb
    container_name: h-j-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deploiement
    ports:
      - "3307:3306"
    volumes:
      - ./BDD/new.sql:/docker-entrypoint-initdb.d/new.sql:ro
      - db_data:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/new.sql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:

